name: Build Sokoban

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: Windows-x64

          - os: windows-11-arm
            name: Windows-ARM64

          - os: ubuntu-latest
            name: Linux-x64

          - os: ubuntu-24.04-arm
            name: Linux-ARM64

          - os: macos-latest
            name: macOS-ARM64

          - os: macos-15-intel
            name: macOS-x64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libgl1-mesa-dev

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Rename Windows executable
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $exe = Get-ChildItem -Path build -Filter "Sokoban.exe" -Recurse | Select-Object -First 1
          if (-not $exe) {
              Write-Host "Couldn't find Sokoban.exe:"
              Get-ChildItem build -Recurse
              exit 1
          }

          Rename-Item $exe.FullName "Sokoban-${{ matrix.name }}.exe"

      - name: Rename Unix executable
        if: runner.os != 'Windows'
        shell: bash
        run: |
          exe=$(find build -type f -name "Sokoban" | head -n 1)

          if [ -z "$exe" ]; then
            echo "Couldn't find Sokoban:"
            find build -type f
            exit 1
          fi

          mv "$exe" "Sokoban-${{ matrix.name }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sokoban-${{ matrix.name }}
          path: build/Sokoban-${{ matrix.name }}*
            
  release:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: release
          
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name: Sokoban ${{ github.ref_name }}
          files: release/**/*
